[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.build]
cmds = ["composer install --no-interaction --prefer-dist --optimize-autoloader"]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
